version: "3.9"

services:
  postgres:
    container_name: diploma_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: "diploma"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"